# Generated by Django 4.2 on 2023-04-09 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('slug', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('post_slug', models.CharField(max_length=9)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=10)),
                ('public', models.BooleanField(default=True)),
                ('publishedAt', models.DateTimeField(null=True)),
                ('viewsCount', models.IntegerField(default=0)),
                ('uniqueViewsCount', models.IntegerField(default=0)),
                ('read', models.BooleanField(default=False)),
                ('modAnsweredAt', models.DateTimeField(null=True)),
                ('answersCount', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.author')),
            ],
        ),
    ]
