# Generated by Django 4.2 on 2023-05-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_author_moderator_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likesCount',
            field=models.IntegerField(default=0),
        ),
    ]
