# Generated by Django 4.2 on 2023-05-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_course_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='posts',
            field=models.ManyToManyField(null=True, to='analytics.post'),
        ),
    ]
