# Generated by Django 4.2 on 2023-05-10 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_author_username_alter_course_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.author'),
        ),
    ]
