# Generated by Django 4.2 on 2023-05-11 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_staff_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.course'),
        ),
    ]
